name: Build & Publish APK

on:
  push:
    branches: [ testing-ci-cd ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/jelly_bean_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: build apk
        run: ./gradlew assembleDebug
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
#          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: newTestGroup
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: A new update!!!!!!!!!!